version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.17
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Verify folder structure
          command: ls -R
      - run:
          name: Install frontend dependencies
          command: cd frontend/frontend && npm ci
      - run:
          name: Build React App
          command: cd frontend/frontend && npm run build
      - run:
          name: Run React tests
          command: cd frontend/frontend && npm test -- --watchAll=false

workflows:
  build_and_test:
    jobs:
      - build
