version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd frontend/frontend && npm install
      - run:
          name: Build React App
          command: cd frontend/frontend && npm run build
      - run:
          name: Run tests
          command: cd frontend/frontend && npm test -- --watchAll=false

workflows:
  build_and_test:
    jobs:
      - build
